// All site copy lives here. Everything is public-safe: it is drawn from the
// owner's public GitHub repos and outward-facing positioning only.
// Do not add private project names, client names, numbers, or revenue claims.

export const profile = {
  name: 'Ezra Wu',
  user: 'ezra',
  host: 'site',
  github: 'https://github.com/qwertyboy0325',
  email: 'ezra40907@gmail.com', // public contact address (buttons and the `contact` line appear when this is a string; null hides them)
};

/** The public address of the site. Used for the canonical link, share previews and the sitemap (a test keeps them in step). */
export const SITE_URL = 'https://qwertyboy0325.github.io/personal-site/';

/** Shown in the status line. Keep in step with package.json (a test checks). */
export const VERSION = '1.0.0';

/** `theme` sets the colour temperature of the page's light: `auto` follows the visitor's local time; `matrix` is an easter egg. */
export const THEMES = ['auto', '5200k', '3400k', '2700k', '2200k', 'matrix'];
export const LANGS = ['en', 'zh'];
export const LANG_NAMES = { en: 'English', zh: '繁體中文' };

// 5-row pixel font used for the banner (kept as data so it is easy to change).
const GLYPHS = {
  E: ['█████', '█    ', '████ ', '█    ', '█████'],
  Z: ['█████', '   █ ', '  █  ', ' █   ', '█████'],
  R: ['████ ', '█   █', '████ ', '█  █ ', '█   █'],
  A: [' ███ ', '█   █', '█████', '█   █', '█   █'],
};
export const banner = Array.from({ length: 5 }, (_, row) =>
  [...'EZRA'].map((ch) => GLYPHS[ch][row]).join('  ').trimEnd(),
).join('\n');

// Public repositories only. Plain language first (for people who do not write
// code), engineering terms in `tech`. `points` and `nongoals` follow each repo's
// own README / ADRs; keep claims bounded to what those documents state.
export const projects = [
  {
    slug: 'handoff-semantics',
    short: 'handoff', // label on the HUD project map
    url: 'https://github.com/qwertyboy0325/handoff-semantics',
    stack: 'C# · .NET 8 · PostgreSQL',
    en: {
      tag: 'Making sure messages between systems are never lost',
      summary:
        'A worked example of a common business problem: a system saves something (say, an order), but the message that tells other systems about it gets lost or is sent twice. It shows how to design this so a saved change is never silently dropped and a repeated message does not cause a repeated effect.',
      tech: 'Reference implementation of transactional outbox, idempotent inbox, SKIP LOCKED multi-worker safety and dead-letter reprocessing, plus a deterministic stale-failure write-race case study.',
      points: [
        'Spells out, step by step, what is guaranteed at each hand-off and what is not.',
        'Automated tests against a real database; one real timing bug is shown failing, then fixed.',
      ],
      nongoals: 'Not a ready-made product or framework, and it does not promise perfect delivery in every situation.',
    },
    zh: {
      tag: '確保系統之間的訊息不會遺失',
      summary:
        '示範一個常見的商業問題：系統把資料存好了（例如一筆訂單），但通知其他系統的訊息卻遺失，或被送了兩次。它說明該怎麼設計，讓已存好的變更不會被默默漏掉，重複收到的訊息也不會造成重複的結果。',
      tech: '參考實作：transactional outbox、idempotent inbox、SKIP LOCKED 多 worker 安全、dead-letter 重新處理，以及可重現的 stale failure write-race 案例。',
      points: [
        '逐一說明每個交接點保證了什麼、沒有保證什麼。',
        '以真實資料庫做自動化測試；一個真實的時序錯誤先被重現（失敗），再被修好。',
      ],
      nongoals: '不是現成的產品或框架，也不保證任何情況下都能完美送達。',
    },
  },
  {
    slug: 'vox-proof',
    short: 'vox', // label on the HUD project map
    url: 'https://github.com/qwertyboy0325/vox-proof',
    stack: 'Rust',
    en: {
      tag: 'A second pair of eyes for subtitles and transcripts',
      summary:
        'Speech-to-text tools make mistakes, especially with mixed Chinese and English, names and abbreviations. This tool reads an existing subtitle file, highlights the places most likely to be wrong, and suggests fixes together with its reasons. A person always makes the final call, and it runs on your own computer.',
      tech: 'Local-first transcript QA in Rust: reviews an existing SRT (optionally with audio), surfaces high-risk spans, and proposes bounded, evidence-backed corrections for human review.',
      points: [
        'It never rewrites text on its own; the human decision is final.',
        'Every suggestion comes with evidence, and every decision is logged.',
      ],
      nongoals: 'It does not do speech recognition itself, does not auto-correct, and has not yet been validated by outside users.',
    },
    zh: {
      tag: '替字幕與逐字稿多一雙眼睛',
      summary:
        '語音轉文字工具常出錯，尤其是中英夾雜、人名和縮寫。這個工具會讀取現有的字幕檔，標出最可能有錯的地方，並附上理由提出修正建議。最後一律由人決定，而且在你自己的電腦上執行。',
      tech: '以 Rust 打造、本機優先的逐字稿 QA：審閱既有的 SRT（可搭配音訊），標出高風險片段，並提出有邊界、有證據的修正建議，交由人工審核。',
      points: [
        '它不會自己改寫文字，人的決定才是最終結果。',
        '每個建議都附上證據，每個決定都有紀錄。',
      ],
      nongoals: '它本身不做語音辨識、不自動修正，也尚未經過外部使用者的驗證。',
    },
  },
  {
    slug: 'echlub',
    short: 'echlub', // label on the HUD project map
    url: 'https://github.com/qwertyboy0325/echlub',
    stack: 'Rust · WASM · TypeScript',
    en: {
      tag: 'The groundwork for making music together online',
      summary:
        'Groundwork for an online tool where people make music together. The effort goes into getting the core rules right first, keeping the part that decides what is true separate from the part that draws it on screen, and measuring real performance before promising anything about speed or delay.',
      tech: 'Clean rewrite of a collaborative-music foundation: a Rust canonical kernel with TypeScript for presentation only (ADR-0002), a transport-independent protocol (ADR-0004), and intent-aware replication with no silent merge (ADR-0005).',
      points: [
        'Key design choices are written down as decision records.',
        'When two people edit at once, conflicts are surfaced openly rather than silently merged.',
      ],
      nongoals: 'Not a finished music app, and it makes no claim of being faster or lag-free.',
    },
    zh: {
      tag: '一起線上做音樂的基礎工程',
      summary:
        '為「多人一起線上做音樂」的工具打基礎。重點是先把核心規則做對：負責判定「什麼才是真的」的部分，和負責畫在螢幕上的部分分開；在承諾速度或延遲之前，先量測真實的效能。',
      tech: '重寫協作音樂系統的基礎：Rust 為權威核心、TypeScript 只負責呈現（ADR-0002）、與傳輸層無關的協定（ADR-0004），以及以意圖為基礎、不做無聲合併的複寫（ADR-0005）。',
      points: [
        '重要的設計決定都寫成決策紀錄。',
        '兩個人同時編輯時，衝突會被明確標示出來，而不是默默合併。',
      ],
      nongoals: '不是完成的音樂應用程式，也不宣稱更快或沒有延遲。',
    },
  },
  {
    slug: 'echlub-demo',
    short: 'demo', // label on the HUD project map
    url: 'https://github.com/qwertyboy0325/echlub-demo',
    stack: 'TypeScript · Tone.js · GSAP',
    en: {
      tag: 'A clickable demo of the music tool idea',
      summary:
        'An interactive demo that shows how the experience of the music tool could feel, built with web audio and animation libraries.',
      tech: 'Built on Tone.js and GSAP, with the audio clock, the script and the animation kept as separate concerns.',
      points: ['Shows the look and feel in your browser.'],
      nongoals: 'A demonstration of the experience only; it is not evidence that the underlying system works.',
    },
    zh: {
      tag: '音樂工具構想的互動展示',
      summary: '互動式展示，呈現這個音樂工具使用起來可能的感覺，以網頁音訊與動畫函式庫製作。',
      tech: '以 Tone.js 與 GSAP 製作，音訊時鐘、腳本與動畫分屬不同關注點。',
      points: ['在瀏覽器裡就能看到操作的質感。'],
      nongoals: '只是體驗的展示，並不是底層系統可運作的證據。',
    },
  },
];

// Other work worth showing. Only public-safe material, written for people who do
// not write code, and de-identified: no private project names, clients, partners
// or numbers. Each item was checked against its source; `nongoals` states what
// is NOT claimed. `url` is set only when a public page exists.
export const works = [
  {
    slug: 'black-hole',
    kind: 'visual',
    url: 'https://github.com/qwertyboy0325/blackhole-rust',
    en: {
      title: 'Black hole renderer',
      tag: 'Drawing how a black hole bends light',
      summary:
        'A program that draws what the space around a black hole looks like. It works out the path of light rays from physics equations, so the glowing ring and the bent starlight come from calculation rather than from painting. The look is inspired by the film Interstellar.',
      tech: 'Offline Rust renderer: Kerr-spacetime geodesic ray tracing (DOP853 integration), physical thin-disk emission and CIE colorimetry, built in reviewed stages ("gates") with written reports.',
      points: [
        'Built in stages: each stage has a written report and has to pass its checks before the next one begins.',
        'An animated before-and-after of every stage is kept in the project.',
      ],
      nongoals: "Not a copy of the film's own software, and not real-time yet (no graphics-card or interactive viewer).",
    },
    zh: {
      title: '黑洞光線渲染器',
      tag: '畫出黑洞如何彎曲光線',
      summary:
        '一個畫出黑洞周圍景象的程式。它用物理公式算出光線的行進路徑，所以發亮的光環和被彎曲的星光是「算」出來的，不是畫出來的。外觀靈感來自電影《星際效應》。',
      tech: '離線 Rust 渲染器：Kerr 時空的測地線光線追蹤（DOP853 積分）、物理薄盤輻射與 CIE 色度學，以分階段（gate）審查並附書面報告的方式開發。',
      points: [
        '分階段開發：每個階段都有書面報告，通過檢查後才進入下一階段。',
        '每個階段的前後對照動畫都保存在專案裡。',
      ],
      nongoals: '不是電影原本軟體的複製品，目前也還不是即時運算（尚無顯示卡加速或互動檢視器）。',
    },
  },
  {
    slug: 'explosion-fx',
    kind: 'visual',
    en: {
      title: 'Explosion effects studies',
      tag: 'Studying how to make explosion effects look convincing',
      summary:
        'A game-engine prototype used as a testbed for cinematic explosion effects: the shape of the fireball, the shock ring, drifting dust, and lighting on a real city district rebuilt from open map data. It is set in a fictional sandbox with made-up parameters.',
      tech: 'Unreal Engine 5.8 C++ prototype with a numbered series of fireball art studies, a city generated from OpenStreetMap data, and a standalone test suite for the simulation logic.',
      points: [
        'A numbered series of written studies shows each round of the effect being reviewed and improved.',
        'The simulation logic has its own automated tests, separate from the game engine.',
      ],
      nongoals: 'A source-code prototype, not a finished or fully tested game; running it end to end in the engine is still to be verified.',
    },
    zh: {
      title: '爆炸特效研究',
      tag: '研究怎麼讓爆炸特效看起來真實',
      summary:
        '用遊戲引擎當實驗場，研究電影級爆炸特效：火球的形狀、衝擊環、飄散的塵雲，以及在用開放地圖資料重建的真實城市街區上打光。場景是虛構的沙盒，所有參數都是假設的。',
      tech: 'Unreal Engine 5.8 的 C++ 原型：一系列編號的火球美術研究、以 OpenStreetMap 資料產生的城市，以及獨立的模擬邏輯測試。',
      points: [
        '一系列編號的書面研究，記錄特效每一輪的檢視與改進。',
        '模擬邏輯有自己的自動化測試，與遊戲引擎分開。',
      ],
      nongoals: '這是原始碼原型，不是完成或完整測試過的遊戲；在引擎中完整跑一遍仍待驗證。',
    },
  },
  {
    slug: 'local-ai',
    kind: 'thinking',
    en: {
      title: 'An AI that has to ask permission',
      tag: 'A personal AI that runs on my own computer and needs a person to approve changes',
      summary:
        'A personal AI assistant that runs entirely on my own computer, so my data does not leave it. It can only use a short list of approved tools, and anything that writes a file waits for a person to approve it first. Results are then checked independently, by file size and a checksum, instead of taking the AI at its word.',
      tech: 'Local-model stack (LM Studio, Open WebUI, Flowise, Letta) behind a tool-allowlisting runtime with audit logs, human approval gates, localhost-only ports, secrets kept in the OS keychain, and SHA-256 verified health reports.',
      points: [
        'A recorded demo shows the safety net working: the AI said it would create a file but never did, and the independent check marked the task as not done.',
        'The demo also lists what did not count as a success, instead of hiding it.',
      ],
      nongoals: 'A personal setup, not a product. The high-privilege coding sandbox is deliberately not started automatically.',
    },
    zh: {
      title: '做事前必須先問過人的 AI',
      tag: '跑在自己電腦上、任何改動都要人批准的個人 AI',
      summary:
        '一個完全在自己電腦上運作的個人 AI 助理，所以資料不會離開這台電腦。它只能使用一份簡短的核准工具清單，凡是要寫入檔案的動作，都得先等人批准。結果再由獨立的檢查（檔案大小與雜湊值）來驗證，而不是直接相信 AI 的說法。',
      tech: '本機模型堆疊（LM Studio、Open WebUI、Flowise、Letta），搭配工具白名單 runtime、稽核紀錄、人工核准閘門、只開本機端口、密鑰存在系統鑰匙圈，以及附 SHA-256 的健康檢查報告。',
      points: [
        '一段錄製的示範呈現了安全網的作用：AI 說要建立檔案卻沒有做，獨立檢查把這個任務判定為未完成。',
        '示範也列出「不算成功」的項目，而不是把它藏起來。',
      ],
      nongoals: '這是個人的設置，不是產品。高權限的程式沙箱刻意不會自動啟動。',
    },
  },
  {
    slug: 'proof-notes',
    kind: 'thinking',
    en: {
      title: 'How to prove a system is right, not just fast',
      tag: 'A checklist for deciding whether a change is safe to release',
      summary:
        'Working notes on deciding whether a change to a map or location search is trustworthy enough to release. The key idea is to keep two questions apart: is the answer right, and is it fast? Each needs a different kind of evidence, and one is never allowed to stand in for the other.',
      tech: 'Correctness proof (oracle comparison on hard cases) versus performance proof (EXPLAIN (ANALYZE, BUFFERS), P50/P95/P99 latency), plus staged rollout behind feature flags.',
      points: [
        'Three levels of proof: checks and tests only; real measurements on hard cases; then a gradual release that is watched in production.',
        'A simple rule: without a comparison against a trusted reference answer, nobody may claim the result is correct.',
      ],
      nongoals: 'Personal working notes, not a published standard or a tool.',
    },
    zh: {
      title: '怎麼證明系統是對的，而不只是很快',
      tag: '判斷一項改動能不能安全上線的檢查清單',
      summary:
        '一份工作筆記，討論怎麼判斷地圖或位置搜尋的改動夠不夠可信、能不能上線。核心想法是把兩個問題分開：答案對不對？速度快不快？兩者需要不同的證據，而且其中一個不能拿來頂替另一個。',
      tech: '正確性證明（在困難案例上與 oracle 對照）對比效能證明（EXPLAIN (ANALYZE, BUFFERS)、P50/P95/P99 延遲），再搭配 feature flag 的漸進式上線。',
      points: [
        '三個證明等級：只做檢查與測試；在困難案例上做實際量測；最後是在線上被監看的漸進式上線。',
        '一條簡單的規則：沒有和可信的參考答案對照，就不能宣稱結果是正確的。',
      ],
      nongoals: '這是個人的工作筆記，不是公開的標準，也不是工具。',
    },
  },
  {
    slug: 'evidence-plan',
    kind: 'thinking',
    en: {
      title: 'A business plan that shows its evidence',
      tag: 'Turning a business idea into claims that can be tested',
      summary:
        'A long business white paper in which every important claim is labelled as a fact, a stand-in measure, or an assumption, with a grade for how strong the evidence is and a next step to firm it up. The point is to keep an exciting idea honest.',
      tech: 'Research evidence ledger: claim inventory, evidence grading (A/B/C), "next evidence" per claim, and a two-week / four-week backlog.',
      points: [
        'Every key claim has a written next step for finding better evidence.',
        'Comes with a market study of competitors and a set of charts.',
      ],
      nongoals: 'The venture itself is private and is not described here; this shows the method only.',
    },
    zh: {
      title: '每個主張都附上證據的商業企劃',
      tag: '把一個商業構想拆成可以被檢驗的主張',
      summary:
        '一份很長的商業白皮書，其中每個重要主張都被標成「事實」「替代指標」或「假設」，並附上證據強度的分級，以及補強證據的下一步。重點是讓一個令人興奮的構想保持誠實。',
      tech: '研究證據清單（evidence ledger）：主張盤點、證據分級（A/B/C）、每個主張的「下一步證據」，以及兩週／四週的待辦。',
      points: [
        '每個關鍵主張都寫明了如何找到更好證據的下一步。',
        '附有競爭對手的市場研究與一組圖表。',
      ],
      nongoals: '該事業本身屬於私人內容，這裡不會描述；這裡只展示方法。',
    },
  },
  {
    slug: 'posture-wearable',
    kind: 'design',
    en: {
      title: 'A backpack that nudges you to sit up straight',
      tag: 'A wearable design proposal that is honest about what is not tested yet',
      summary:
        'A design proposal for a wearable that notices when your posture slumps and nudges you with soft air cushions and small vibrations, instead of loud alarms. The same sensing core can be worn with or without a bag. It was prepared by a team for a university course on wearable technology.',
      tech: 'Flex-sensor sensing with per-user calibration, paired air bladders and haptic cues, a detachable-bag modular architecture; an Arduino prototype demonstrates one calibrated sensor.',
      points: [
        'It guides rather than forces: it only nudges, and the person stays in control.',
        'The slides separate what was actually demonstrated from what is only proposed, and mark all three configurations as not yet physically tested.',
      ],
      nongoals: 'Not a medical device and not a diagnosis; the design has not been tested on people.',
    },
    zh: {
      title: '會輕輕提醒你坐直的背包',
      tag: '一份誠實標明「還沒測試什麼」的穿戴裝置設計提案',
      summary:
        '一份穿戴裝置的設計提案：它會察覺你姿勢變得鬆垮，並用柔軟的氣囊與輕微的振動提醒你，而不是響亮的警報。同一個感測核心可以搭配背包使用，也可以不帶包單獨穿戴。這是由團隊為一門大學穿戴科技課程準備的。',
      tech: '以 Flex 感測器搭配個人化校正、成對氣囊與觸覺提示、可拆換包體的模組化架構；以 Arduino 原型展示單一已校正的感測器。',
      points: [
        '它是「引導」而不是「強制」：只輕輕提醒，由使用者自己掌控。',
        '簡報把「實際展示過的」和「只是提案的」分開，並標明三種配置都尚未經過實體驗證。',
      ],
      nongoals: '不是醫療器材，也不是診斷；這個設計還沒有在人身上測試過。',
    },
  },
];

// Pictures and video for `view` / the overview. Every file lives in assets/gallery
// and was made from the owner's own public project (see assets/gallery/SOURCES.md).
// width/height are the real pixel sizes (tests check them) so the page never jumps
// while images load. Captions are plain and say what the picture is NOT.
export const gallery = [
  {
    slug: 'black-hole-presentation',
    kind: 'image',
    work: 'black-hole',
    src: 'assets/gallery/black-hole-presentation.jpg',
    width: 1024, height: 1024,
    thumb: 'assets/gallery/black-hole-presentation-thumb.jpg', thumbWidth: 480, thumbHeight: 480,
    source: 'https://github.com/qwertyboy0325/blackhole-rust',
    en: {
      title: 'A black hole, prepared for viewing',
      caption: 'The dark half-oval is the black hole\'s shadow. The bright band curving around it is light from the glowing disk around the hole, bent by gravity. This is the picture after it has been adjusted to look right on a screen. It is a work in progress, not a film-quality image.',
      alt: 'A black half-oval shape at the centre, with a smooth bright blue-white band curving around it against a soft grey-brown background.',
    },
    zh: {
      title: '準備好給人看的黑洞',
      caption: '中間黑色的半橢圓是黑洞的陰影，繞著它彎曲的明亮光帶，是黑洞周圍發光圓盤的光線被引力彎曲的結果。這是調整到適合在螢幕上觀看之後的畫面。它還在進行中，不是電影等級的畫質。',
      alt: '畫面中央有一個黑色的半橢圓，周圍環繞著一道柔和明亮的藍白色光帶，背景是柔和的灰褐色。',
    },
  },
  {
    slug: 'black-hole-scene',
    kind: 'image',
    work: 'black-hole',
    src: 'assets/gallery/black-hole-scene.jpg',
    width: 640, height: 640,
    thumb: 'assets/gallery/black-hole-scene-thumb.jpg', thumbWidth: 480, thumbHeight: 480,
    source: 'https://github.com/qwertyboy0325/blackhole-rust',
    en: {
      title: 'A later stage, with more of the surroundings',
      caption: 'A later stage of the same project that adds the structure of the glowing disk and the background sky. Compared with the earlier pictures, the area around the black hole has more shape and detail.',
      alt: 'A black half-oval shape with a bright curved band around it, now with darker blue areas and more texture around the edges.',
    },
    zh: {
      title: '較後期的階段，周圍多了更多細節',
      caption: '同一個專案較後期的階段，加入了發光圓盤的結構和背景星空。和較早的畫面相比，黑洞周圍的形狀和細節變多了。',
      alt: '一個黑色的半橢圓，周圍有明亮的弧形光帶，邊緣出現更多深藍色區塊與質感。',
    },
  },
  {
    slug: 'black-hole-diagnostic',
    kind: 'image',
    work: 'black-hole',
    src: 'assets/gallery/black-hole-diagnostic.jpg',
    width: 640, height: 640,
    thumb: 'assets/gallery/black-hole-diagnostic-thumb.jpg', thumbWidth: 480, thumbHeight: 480,
    source: 'https://github.com/qwertyboy0325/blackhole-rust',
    en: {
      title: 'An early check, not meant to look good',
      caption: 'An output from an early stage. The picture labels itself "not a beauty render": it exists so the numbers can be checked, not to look good. The black shape is the black hole\'s shadow.',
      alt: 'A grey-scale image with a black oval shape in the lower middle and a lighter curved band around it. A label at the top names the stage.',
    },
    zh: {
      title: '早期的檢查圖，本來就不求好看',
      caption: '早期階段的輸出。圖上自己標明了「不是美術渲染」：它的用途是讓數字可以被檢查，不是為了好看。黑色的形狀是黑洞的陰影。',
      alt: '一張灰階圖片，下方中間有一個黑色的橢圓，周圍有一道較亮的弧形光帶。上方的標籤寫著這個階段的名稱。',
    },
  },
  {
    slug: 'black-hole-evolution',
    kind: 'video',
    work: 'black-hole',
    src: 'assets/gallery/black-hole-evolution.mp4',
    poster: 'assets/gallery/black-hole-evolution-poster.jpg',
    width: 640, height: 640,
    thumb: 'assets/gallery/black-hole-evolution-thumb.jpg', thumbWidth: 480, thumbHeight: 480,
    source: 'https://github.com/qwertyboy0325/blackhole-rust',
    en: {
      title: 'The picture getting better, stage by stage',
      caption: 'A short animation of the project\'s progress. Each frame is the output of one stage of the work, in order, from the first numerical checks to the rendered images.',
      alt: 'An animation that steps through the black hole renderer\'s output at each stage, starting with a title card and ending with a four-panel comparison.',
    },
    zh: {
      title: '畫面一階段一階段變好的過程',
      caption: '專案進度的短動畫。每一格都是某個階段的輸出，依序呈現，從最初的數值檢查一路到渲染出來的畫面。',
      alt: '一段動畫，依序顯示黑洞渲染器在各個階段的輸出，從標題卡開始，最後是四格對照圖。',
    },
  },
  {
    slug: 'photo-backpack-on-the-grass',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-backpack-on-the-grass.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-backpack-on-the-grass-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 35mm f/1.8 S', focal: 35, aperture: 1.8, shutter: '1/3200', iso: 100 },
    en: {
      title: 'A backpack resting on the grass',
      caption: 'A canvas backpack with a steel mug clipped to it, set down on a lawn beside a path in bright sunshine.',
      alt: 'An olive canvas backpack with a steel mug tied to its side, lying on short grass beside a path, with a wooden fence blurred in the background.',
    },
    zh: {
      title: '草地上的背包',
      caption: '一個掛著金屬杯的帆布背包，放在步道旁的草地上，陽光明亮。',
      alt: '一個橄欖綠的帆布背包，側邊綁著一個金屬杯，放在步道旁的短草地上，背景是模糊的木欄杆。',
    },
  },
  {
    slug: 'photo-looking-back',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-looking-back.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-looking-back-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 35mm f/1.8 S', focal: 35, aperture: 1.8, shutter: '1/3200', iso: 100 },
    en: {
      title: 'Looking back',
      caption: 'A person turns to look back at the camera, framed by grassy banks against a deep blue sky. Shot with a wide lens held low.',
      alt: 'A person in a white striped sweater and dark trousers turns to look over their shoulder, standing between two grassy banks under a clear blue sky.',
    },
    zh: {
      title: '回頭看',
      caption: '一個人回頭看向鏡頭，兩側是草坡，頭上是深藍色的天空。用廣角鏡頭從低處拍攝。',
      alt: '一個穿著白色條紋毛衣和深色長褲的人，站在兩片草坡之間，轉頭看向鏡頭，天空晴朗湛藍。',
    },
  },
  {
    slug: 'photo-ridge-in-the-sun',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-ridge-in-the-sun.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-ridge-in-the-sun-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 35mm f/1.8 S', focal: 35, aperture: 3.5, shutter: '1/2500', iso: 100 },
    en: {
      title: 'A grassy ridge in the sun',
      caption: 'Sunlit grass on the side of a ridge, with a long line of hill against a clear sky.',
      alt: 'Tall dry grass in the foreground leading up to a sunlit ridge, with a line of hill and a clear blue sky above.',
    },
    zh: {
      title: '陽光下的草稜',
      caption: '陽光照著山稜側面的草，遠處是一長條山線，天空清澈。',
      alt: '前景是高高的乾草，延伸向被陽光照亮的山稜，上方是一道山線和清澈的藍天。',
    },
  },
  {
    slug: 'photo-looking-at-the-mountain',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-looking-at-the-mountain.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-looking-at-the-mountain-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 35mm f/1.8 S', focal: 35, aperture: 2, shutter: '1/8000', iso: 100 },
    en: {
      title: 'Looking at the mountain',
      caption: 'A person with a backpack stands in tall grass, seen from behind, looking out towards a distant mountain.',
      alt: 'Seen from behind, a person in a light jacket with a green backpack stands in tall grass looking towards a rounded mountain under a pale sky.',
    },
    zh: {
      title: '望向山',
      caption: '一個背著背包的人站在高高的草叢裡，從背後拍攝，望向遠方的山。',
      alt: '從背後看，一個穿淺色外套、背著綠色背包的人站在高草叢中，望向淡藍天空下圓潤的山。',
    },
  },
  {
    slug: 'photo-walker-on-the-path',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-walker-on-the-path.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-walker-on-the-path-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 35mm f/1.8 S', focal: 35, aperture: 2.5, shutter: '1/2000', iso: 100 },
    en: {
      title: 'A walker on the path',
      caption: 'A small figure walks up a narrow path through grassy hills, with a mountain behind.',
      alt: 'A tiny person with a backpack walking up a narrow dirt path that winds through dry grass, with a mountain and hills in the distance.',
    },
    zh: {
      title: '步道上的行人',
      caption: '一個小小的身影沿著狹窄的小路走上草坡，後面是一座山。',
      alt: '一個背著背包的小小身影，沿著蜿蜒穿過乾草的窄土路往上走，遠處是山和丘陵。',
    },
  },
  {
    slug: 'photo-three-posts',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-three-posts.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-three-posts-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 14-24mm f/2.8 S', focal: 14, aperture: 7.1, shutter: '1/500', iso: 100 },
    en: {
      title: 'Three posts against the sky',
      caption: 'Three tall maroon posts with golden Chinese characters, shot from low down with a very wide lens.',
      alt: 'Three tall maroon posts with yellow Chinese characters at their tops, seen from low down against a deep blue sky, with dry grass at the bottom.',
    },
    zh: {
      title: '天空下的三根柱子',
      caption: '三根高高的深紅色柱子，頂端有金色的漢字，用超廣角鏡頭從低處拍攝。',
      alt: '三根高高的深紅色柱子，頂端有黃色漢字，從低處仰拍，背景是深藍色天空，底部有乾草。',
    },
  },
  {
    slug: 'photo-dog-on-the-path',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-dog-on-the-path.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-dog-on-the-path-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 14-24mm f/2.8 S', focal: 24, aperture: 2.8, shutter: '1/800', iso: 100 },
    en: {
      title: 'A dog coming up the path',
      caption: 'A dog in a harness walks towards the camera with its tongue out; a small figure waits further down the path.',
      alt: 'A brown and black dog wearing a green harness walks towards the camera on a dry grass path, with a tiny distant person and hills behind.',
    },
    zh: {
      title: '走過來的狗',
      caption: '一隻穿著胸背帶的狗吐著舌頭走向鏡頭，遠處的小路上有個小小的身影在等。',
      alt: '一隻棕黑色、穿著綠色胸背帶的狗，走在乾草小路上朝鏡頭走來，後方有一個很小的人影和丘陵。',
    },
  },
  {
    slug: 'photo-warm-light-on-concrete',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-warm-light-on-concrete.jpg',
    width: 1065, height: 1600,
    thumb: 'assets/gallery/photo-warm-light-on-concrete-thumb.jpg', thumbWidth: 319, thumbHeight: 480,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 35mm f/1.8 S', focal: 35, aperture: 1.8, shutter: '1/1000', iso: 100 },
    en: {
      title: 'Warm light on a concrete wall',
      caption: 'A portrait of a person sitting against a concrete wall, lit by warm low sunlight.',
      alt: 'A person with short dark hair and a fringe, in a white striped sweater, sitting against a pale concrete wall in warm sunlight and looking at the camera.',
    },
    zh: {
      title: '混凝土牆上的暖光',
      caption: '一個人坐在混凝土牆邊的肖像，被低角度的暖色陽光照亮。',
      alt: '一個留著深色短髮和瀏海、穿白色條紋毛衣的人，坐在淺色混凝土牆邊，在暖色陽光下看著鏡頭。',
    },
  },
  {
    slug: 'photo-close-portrait',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-close-portrait.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-close-portrait-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 35mm f/1.8 S', focal: 35, aperture: 1.8, shutter: '1/640', iso: 100 },
    en: {
      title: 'A close portrait',
      caption: 'A close portrait of a smiling person with glasses, with a concrete arch and flowing water behind.',
      alt: 'A smiling person with round glasses and a white striped sweater, shown from the chest up, with a grey concrete arch and a bright strip of water behind.',
    },
    zh: {
      title: '近距離肖像',
      caption: '一個戴眼鏡、微笑的人的近距離肖像，後面是混凝土拱形和流動的水。',
      alt: '一個戴著圓框眼鏡、穿白色條紋毛衣、面帶微笑的人，拍到胸口以上，後方是灰色混凝土拱形和一條明亮的水。',
    },
  },
  {
    slug: 'photo-two-in-the-light',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-two-in-the-light.jpg',
    width: 1065, height: 1600,
    thumb: 'assets/gallery/photo-two-in-the-light-thumb.jpg', thumbWidth: 319, thumbHeight: 480,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 35mm f/1.8 S', focal: 35, aperture: 1.8, shutter: '1/640', iso: 100 },
    en: {
      title: 'Two people in the light',
      caption: 'Two people lean close together and look downwards, in soft glowing light.',
      alt: 'Two people with dark hair, one wearing glasses, lean their heads together and look downwards, lit by a warm glow with a pale wall behind.',
    },
    zh: {
      title: '光裡的兩個人',
      caption: '兩個人把頭靠得很近，一起往下看，柔和的光暈籠罩著他們。',
      alt: '兩個深色頭髮的人，其中一個戴眼鏡，頭靠在一起往下看，暖色的光暈照亮他們，後面是淺色的牆。',
    },
  },
  {
    slug: 'photo-sun-over-the-valley',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-sun-over-the-valley.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-sun-over-the-valley-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 14-24mm f/2.8 S', focal: 14, aperture: 22, shutter: '1/125', iso: 100 },
    en: {
      title: 'Sun over a valley',
      caption: 'The sun just above a mountain, with a green meadow and winding paths in the foreground. Shot very wide.',
      alt: 'A wide view of a green grassy valley with winding paths, a mountain on the right and the sun shining as a bright star above its edge in a blue sky.',
    },
    zh: {
      title: '山谷上的太陽',
      caption: '太陽剛好在山的上方，前景是綠色草地和蜿蜒的小路。用很廣的鏡頭拍攝。',
      alt: '寬廣的綠色草地山谷，有蜿蜒的小路，右邊是一座山，太陽在山邊上方閃耀成一顆亮星，天空湛藍。',
    },
  },
  {
    slug: 'photo-figure-on-the-lawn',
    kind: 'image',
    set: 'photo',
    src: 'assets/gallery/photo-figure-on-the-lawn.jpg',
    width: 1600, height: 1065,
    thumb: 'assets/gallery/photo-figure-on-the-lawn-thumb.jpg', thumbWidth: 480, thumbHeight: 319,
    shot: { camera: 'NIKON Z 6', lens: 'NIKKOR Z 14-24mm f/2.8 S', focal: 24, aperture: 20, shutter: '1/25', iso: 100 },
    en: {
      title: 'A figure on the lawn',
      caption: 'A person in a deep red robe stands on a lawn, seen from behind, small against low hills and a wide sky.',
      alt: 'A person in a long deep red robe seen from behind, standing on a green lawn with low hills and a fence in the distance under a pale blue sky.',
    },
    zh: {
      title: '草地上的身影',
      caption: '一個穿著深紅色長袍的人站在草地上，從背後拍攝，在低矮的丘陵和寬闊的天空下顯得很小。',
      alt: '一個穿著深紅色長袍的人，從背後看，站在綠色草地上，遠處是低矮的丘陵和欄杆，天空是淡藍色。',
    },
  },
];

/**
 * What the home page shows, by slug (src/page.js renders it). The words for each part live in ui[lang].page.
 * `photos` pick the photographs for the page itself, in order; every one of them stays in `gallery` for the viewer
 * and the terminal. The grid alternates shapes, so keep the order: wide, tall, three upright, one panorama.
 */
export const home = {
  hero: 'photo-sun-over-the-valley',
  photos: ['photo-ridge-in-the-sun', 'photo-warm-light-on-concrete', 'photo-dog-on-the-path', 'photo-looking-back', 'photo-three-posts', 'photo-figure-on-the-lawn'],
  lab: { render: 'black-hole-presentation', renderWork: 'black-hole', letters: 'photo-walker-on-the-path', more: ['explosion-fx'] },
  workDocs: ['local-ai', 'proof-notes', 'evidence-plan', 'posture-wearable'],
};

export const skillGroups = [
  {
    key: 'fix',
    en: ['What I fix', ['Things that happen twice, or not at all (retries and duplicates)', 'Messages that get lost between systems (outbox / inbox)', 'Several workers editing the same data at the same time', 'Database changes that are all-or-nothing, safe upgrades, and each customer\'s data kept apart']],
    zh: ['我處理的問題', ['同一件事做了兩次、或根本沒做（重試與重複）', '訊息在系統之間遺失（outbox / inbox）', '多個工作程序同時修改同一份資料', '資料庫的修改要嘛全成功、要嘛全不動；安全升級；各客戶的資料互相隔離']],
  },
  {
    key: 'tools',
    en: ['Tools I build with', ['C# / .NET 8', 'Rust', 'TypeScript', 'Go', 'PostgreSQL (database)']],
    zh: ['我使用的工具', ['C# / .NET 8', 'Rust', 'TypeScript', 'Go', 'PostgreSQL（資料庫）']],
  },
  {
    key: 'practice',
    en: ['How I work', ['Reproduce the problem on purpose, then prove the fix', 'Automated tests, including against a real database', 'Design decisions written down', 'Only claim what the tests and documents support']],
    zh: ['我的做法', ['刻意重現問題，再證明修復有效', '自動化測試，包含對真實資料庫的測試', '把設計決定寫下來', '只主張測試與文件能證明的事']],
  },
];

export const ui = {
  en: {
    role: 'Backend / Platform Engineer',
    page: {
      nav: { label: 'Sections', photos: 'Photos', lab: 'Lab', work: 'Work', about: 'About', contact: 'Contact', top: 'Back to the top' },
      line: 'I write backend systems for a living. Outside work, I study light: with a camera, and with code.',
      lookHint: 'Move the pointer over the photo',
      now: { label: 'Lately', items: [['Building', 'The next stage of the black hole renderer'], ['Thinking about', 'Letting an AI act only after a person says yes']] },
      photos: { title: 'Photos', intro: 'Mostly a 35mm prime and an ultra-wide, often with the aperture wide open. Many of them are people standing small in a big landscape.', all: (n) => `All ${n} photos`, gear: 'NIKON Z 6 · 35mm f/1.8 · 14–24mm f/2.8', open: 'Open larger' },
      lab: {
        title: 'Lab',
        intro: 'Light a camera cannot catch, I work out with code. Light it did catch, I take apart into letters. Each experiment starts from a question.',
        renderQ: 'If gravity bends light, what does the picture look like?',
        renderMeta: 'Rust · offline renderer',
        source: 'Source',
        lettersQ: 'How few letters does it take to recognise someone?',
        lettersBody: 'The mirror draws your camera as letters, live, on your own device. It is waiting at the bottom of this page.',
        lettersMeta: 'camera · stays on your device',
        lettersGo: 'Go to the mirror',
        computed: 'light, worked out',
        written: 'light, written',
        model: 'Text 3D',
        modelBody: 'A spinning model drawn in letters, with light and shadow. The pointer turns it.',
        inTerminal: 'Open in the terminal',
      },
      work: { title: 'Work', intro: 'By day I build backend systems: databases, background jobs, and the messages that pass between parts of a system. Here are the public projects and a few documents.', code: 'Code', docs: 'Writing', kinds: { thinking: 'thinking', design: 'design' } },
      about: {
        title: 'About',
        lead: 'I photograph light, work it out with code, and take it apart into letters.',
        body: [
          'I am Ezra, a backend and platform engineer. I help teams that already have a working product with the parts nobody sees: the database, the background jobs, and the way different parts of a system pass messages to each other.',
          'Outside work I take pictures, render light from physics, and turn photographs into text. Every picture on this site appears as letters first.',
        ],
        facts: [['Camera', 'Nikon Z 6'], ['Lenses', '35mm f/1.8, 14–24mm f/2.8'], ['Code', 'C# / .NET, Rust, TypeScript, Go, PostgreSQL'], ['Languages', '中文, English'], ['Work with me', 'Reliability problems behind a product that already runs']],
        faceLabel: 'A face drawn in letters that follows the pointer',
        faceHint: 'There is no photo of me here. Move the pointer and it looks at you; type and it talks.',
      },
      mirror: {
        title: 'The last photo is you',
        intro: 'Every picture above was someone else\'s light. This one is yours: your camera, drawn as letters on your own device.',
        privacy: 'Only on your device · nothing recorded · nothing uploaded',
        shutter: 'Take a picture',
        prints: 'Prints',
        printsEmpty: 'Press the shutter and the frame is printed here as text you can copy.',
        copy: 'Copy as text',
        copied: 'Copied',
        cols: (n) => `${n} columns`,
      },
      contact: { title: 'Want to make something together, or just talk about light?', copy: 'Copy', github: 'GitHub' },
      colophon: 'No cookies, no trackers. Every picture appears as letters first.',
      light: (time, k) => `Your local time ${time} · this page is lit at about ${k}K`,
      lightFixed: (k) => `This page is lit at about ${k}K`,
      terminal: { open: 'Open the terminal', close: 'Close the terminal', title: 'terminal', hint: '~ opens and closes it · Esc closes it' },
      lang: '中文',
    },
    documentTitle: 'Ezra Wu — Backend / Platform Engineer',
    status: { claims: '0 cookies · 0 trackers · 0 dependencies', label: 'Site details' },
    ogLine: 'I make the behind-the-scenes parts of software reliable: no lost messages, no repeated actions, no overwritten data.',
    inputLabel: 'Command input',
    chipsLabel: 'Quick commands',
    skip: 'Skip to content',
    themeButton: 'Change the colour temperature of the light',
    langButton: 'Switch language',
    welcome: 'I make the behind-the-scenes parts of software reliable: no lost messages, no repeated actions, no overwritten data.',
    welcomeHint: ['Type ', { cmd: 'help' }, ' or tap a command below. Tab completes, ↑ recalls.'],
    boot: ['loading profile', 'mounting /projects', 'ready'],
    bootCount: (n) => `mounting /projects (${n} public repositories)`,
    cmds: {
      about: 'who I am and how I work',
      projects: 'things I have built (public)',
      works: 'other work worth a look',
      gallery: 'pictures and a video',
      photos: 'my photographs',
      view: 'show one picture',
      work: 'details of one piece of work',
      skills: 'what I can help with',
      contact: 'how to reach me',
      ls: 'list files',
      cat: 'print a file',
      open: 'open a link in a new tab',
      theme: 'auto | 5200k | 3400k | 2700k | 2200k',
      lang: 'en | zh',
      ascii: 'an ASCII face that watches you',
      '3d': 'a spinning 3D model made of text',
      transition: 'auto | dissolve | scan | rain | off',
      mode: 'one page at a time, or a scrolling log (page | log)',
      mirror: 'see yourself drawn in letters (camera; stays on your device)',
      clear: 'clear the screen',
      history: 'previous commands',
      help: 'this list',
    },
    asciiLabel: 'Animated ASCII face',
    asciiHint: 'Move the pointer: it watches. Type: it listens.',
    modelLabel: (shape) => `Spinning ASCII 3D model: ${shape}`,
    modelHint: ['Move the pointer to steer it. Try ', { cmd: '3d cube' }, ', ', { cmd: '3d sphere' }, ' or ', { cmd: '3d donut' }, '.'],
    modelBad: (q, all) => `3d: unknown shape "${q}" (available: ${all})`,
    transitionCurrent: (cur, all) => `transition: ${cur}   (available: ${all})`,
    transitionSet: (m) => `ASCII transition set to ${m}`,
    transitionBad: (q, all) => `transition: unknown mode "${q}" (available: ${all})`,
    mirror: {
      label: 'Camera mirror',
      intro: 'See yourself drawn in letters. Your camera is used only after you press the button, and only on this page: the picture is turned into text on your device. Nothing is recorded, saved or sent anywhere.',
      start: '▶ Turn on camera',
      stop: '■ Stop',
      copy: 'Copy this frame as text',
      copyShort: 'Copy as text',
      fullscreen: 'Full screen',
      closeStage: 'Close and turn the camera off',
      copied: 'Copied this frame as text',
      copyFailed: 'Could not copy',
      hint: 'Esc, ✕ or Stop turns the camera off.',
      starting: 'Waiting for the camera…',
      slowStart: 'Still waiting. If your browser is asking for permission, choose Allow; or press Stop and try again.',
      live: 'Camera on. Nothing is recorded.',
      off: 'Camera off.',
      pausedHidden: 'Camera turned off because this tab was hidden.',
      lost: 'The camera was disconnected.',
      errors: {
        denied: 'The camera is blocked. Allow it for this site in your browser (look for the camera icon in the address bar), then try again.',
        none: 'No camera was found on this device.',
        busy: 'The camera is being used by another app.',
        insecure: 'The camera only works on secure (https) pages.',
        unsupported: 'This browser cannot open a camera from a web page.',
        other: 'The camera could not be started.',
      },
    },
    modeCurrent: (cur, all) => `mode: ${cur}   (available: ${all}; "page" shows one page at a time like a document, "log" keeps every command's output and scrolls like a classic terminal)`,
    modeSet: (m) => `mode ${m}`,
    modeBad: (q, all) => `mode: unknown mode "${q}" (available: ${all})`,
    pages: { home: 'Home', about: 'About', projects: 'Projects', works: 'Works', gallery: 'Gallery', photos: 'Photos', skills: 'Skills', contact: 'Contact', help: 'Help', mirror: 'Mirror' },
    helpTitle: 'Available commands',
    helpFooter: ['Tip: ', { cmd: 'ls' }, ' shows files, ', { cmd: 'cat about.md' }, ' reads one. Shortcuts: Tab, ↑/↓, Ctrl+L.'],
    aboutTitle: 'about',
    bio: [
      'I am a software engineer (Backend / Platform Engineer). I help teams that already have a working product fix the hidden reliability problems behind it: the database, the background jobs, and the way different parts of a system pass messages to each other.',
      'My specialty is failures that look safe but are not: something that can occasionally happen twice, get lost, or be overwritten. Think of an order that is saved but never announced to the warehouse, or a notification that goes out twice.',
      'Work is fixed-scope: a diagnosis, a review of the design and code, reproducing the problem on purpose, then the fix. Everything is written down, communication is asynchronous, and payment follows milestones.',
    ],
    workStyleTitle: 'how I work',
    workStyle: 'I do not just say it works; I show how I know. Every claim is tied to a test, a document, or an honest note of what is not claimed. When something goes wrong in timing or in the numbers, I make it visible instead of smoothing it over.',
    aboutNext: ['Next: ', { cmd: 'projects' }, ', ', { cmd: 'skills' }, ', ', { cmd: 'contact' }],
    galleryTitle: 'gallery',
    galleryWorksHeading: 'from my projects',
    galleryPhotosHeading: 'photographs',
    photosTitle: 'photos',
    photosHint: (n) => ['Run ', { cmd: `view ${n}` }, ' (or a name). Shooting details are shown under each photo; click it for a larger view.'],
    galleryHint: ['Run ', { cmd: 'view 1' }, ' (or a name). The picture is drawn in characters first, then turns into the real thing; click it for a larger view.'],
    viewUsage: ['usage: view <number | name>   (see ', { cmd: 'gallery' }, ')'],
    noView: (q) => `view: no match for "${q}"`,
    viewer: {
      open: 'Open larger',
      close: 'Close',
      prev: 'Previous',
      next: 'Next',
      counter: (i, n) => `${i} / ${n}`,
      source: 'source',
      play: 'video',
      related: 'about this',
      pictures: 'pictures',
      label: 'Picture viewer',
    },
    worksTitle: 'works',
    worksHint: ['Run ', { cmd: 'work 1' }, ' (or a name) for details. These are described without private names, partners or figures.'],
    workKinds: { visual: 'Visual and 3D', thinking: 'Research and thinking', design: 'Design' },
    workLabels: { kind: 'kind', repo: 'repo' },
    workUsage: ['usage: work <number | name>   (see ', { cmd: 'works' }, ')'],
    noWork: (q) => `work: no match for "${q}"`,
    projectsTitle: 'projects',
    projectsHint: ['Public projects. Run ', { cmd: 'project 1' }, ' (or a name) for details.'],
    projectLabels: { stack: 'built with', repo: 'repo', notes: 'not claimed', tech: 'for engineers' },
    skillsTitle: 'skills',
    contactTitle: 'contact',
    contactLabels: { github: 'github', email: 'email', mode: 'how' },
    contactCopy: 'copy',
    contactButton: 'Copy email address',
    contactCopied: 'Email address copied',
    contactFailed: (addr) => `Could not copy automatically. The address is ${addr}`,
    contactMode: 'Tell me what is going wrong in plain words, and what system you use if you know. I reply in writing.',
    labels: { language: 'language', theme: 'theme', role: 'role', repos: 'repos', shell: 'shell' },
    notFound: (c) => `command not found: ${c}`,
    didYouMean: (c) => ['Did you mean ', { cmd: c }, '?'],
    tryHelp: ['Type ', { cmd: 'help' }, ' for the list of commands.'],
    noFile: (p) => `cat: ${p}: No such file or directory`,
    isDir: (p) => `cat: ${p}: Is a directory`,
    notDir: (p) => `ls: ${p}: Not a directory`,
    noSuchDir: (p) => `ls: ${p}: No such file or directory`,
    catUsage: ['usage: cat <file>   (try ', { cmd: 'ls' }, ')'],
    noProject: (q) => `project: no match for "${q}"`,
    projectUsage: ['usage: project <number | name>'],
    openUsage: (names) => `usage: open <${names}>`,
    openBad: (q) => `open: unknown target "${q}"`,
    opening: (u) => `opening ${u}`,
    themeCurrent: (cur, all) => `theme: ${cur}   (available: ${all})`,
    themeSet: (t) => `theme set to ${t}`,
    themeBad: (q, all) => `theme: unknown theme "${q}" (available: ${all})`,
    langCurrent: (cur) => `language: ${cur}   (available: en, zh)`,
    langSet: (n) => `language set to ${n}`,
    langBad: (q) => `lang: unknown language "${q}" (available: en, zh)`,
    historyEmpty: 'history is empty',
    whoami: 'ezra, Backend / Platform Engineer',
    sudo: 'ezra is not in the sudoers file. This incident will be reported.',
    exit: 'There is no exit, only `help`.',
    completions: 'matches',
  },
  zh: {
    role: '後端／平台工程師',
    page: {
      nav: { label: '區塊', photos: '照片', lab: '實驗', work: '工作', about: '關於', contact: '聯絡', top: '回到最上面' },
      line: '寫後端系統的工程師。工作以外，我用相機和程式研究光。',
      lookHint: '把游標移到照片上',
      now: { label: '最近', items: [['正在做', '黑洞渲染器的下一個階段'], ['正在想', '讓 AI 動手之前，先問過人']] },
      photos: { title: '照片', intro: '大多是 35mm 定焦和超廣角，光圈常常開到最大。很多張都是人站在很大的風景裡。', all: (n) => `看全部 ${n} 張`, gear: 'NIKON Z 6 · 35mm f/1.8 · 14–24mm f/2.8', open: '放大檢視' },
      lab: {
        title: '實驗',
        intro: '相機拍不到的光，我用程式去算；拍到的光，我把它拆成字。每個實驗都從一個問題開始。',
        renderQ: '如果光會被重力彎曲，畫面會長成什麼樣子？',
        renderMeta: 'Rust · 離線渲染',
        source: '原始碼',
        lettersQ: '一個人最少要幾個字，才認得出是誰？',
        lettersBody: '鏡子會用你的相機，即時把你畫成字元，只在你的裝置上處理。它在這一頁的最下面等你。',
        lettersMeta: '相機 · 只留在你的裝置',
        lettersGo: '到鏡子那裡',
        computed: '算出來的光',
        written: '寫成字的光',
        model: '文字 3D',
        modelBody: '用字元畫的旋轉模型，有光影也有遮擋，游標控制轉動。',
        inTerminal: '在終端機打開',
      },
      work: { title: '工作', intro: '白天我寫後端系統，處理資料庫、背景工作，以及系統之間傳遞的訊息。下面是公開的專案和幾份文件。', code: '程式', docs: '文件', kinds: { thinking: '思考', design: '設計' } },
      about: {
        title: '關於',
        lead: '我拿相機拍光，用程式算光，也把光拆成字。',
        body: [
          '我是 Ezra，後端／平台工程師。我協助已經有產品在運作的團隊，處理那些沒人看得見的部分：資料庫、背景工作，以及系統各部分之間傳遞訊息的方式。',
          '工作以外，我拍照、用物理公式渲染光，也把照片轉成文字。這個網站上的每一張圖，都會先以字元的樣子出現。',
        ],
        facts: [['相機', 'Nikon Z 6'], ['常用鏡頭', '35mm f/1.8、14–24mm f/2.8'], ['程式', 'C# / .NET、Rust、TypeScript、Go、PostgreSQL'], ['語言', '中文、English'], ['合作', '已經在運作的產品背後的可靠性問題']],
        faceLabel: '一張用字元畫的臉，會跟著游標看',
        faceHint: '網站上沒有我的照片。移動游標，它會看著你；你打字的時候，它的嘴巴會動。',
      },
      mirror: {
        title: '最後一張照片是你',
        intro: '上面每一張都是別人的光。這一張是你的：你的相機，在你自己的裝置上被畫成字元。',
        privacy: '只在你的裝置上 · 不錄影 · 不上傳',
        shutter: '按下快門',
        prints: '印樣',
        printsEmpty: '按下快門，這一格會變成可以複製的文字，印在這裡。',
        copy: '複製成文字',
        copied: '已複製',
        cols: (n) => `${n} 欄`,
      },
      contact: { title: '想一起做點什麼，或只是聊聊光？', copy: '複製', github: 'GitHub' },
      colophon: '沒有 cookie，沒有追蹤器。每張圖都先以字元出現。',
      light: (time, k) => `你那裡現在 ${time} · 這一頁的光約 ${k}K`,
      lightFixed: (k) => `這一頁的光約 ${k}K`,
      terminal: { open: '打開終端機', close: '關閉終端機', title: '終端機', hint: '按 ~ 打開或關閉 · Esc 關閉' },
      lang: 'English',
    },
    documentTitle: 'Ezra Wu — 後端／平台工程師',
    status: { claims: '0 個 cookie · 0 個追蹤器 · 0 個依賴套件', label: '網站資訊' },
    ogLine: '我讓軟體幕後的部分更可靠：不漏訊息、不重複執行、不覆蓋資料。',
    inputLabel: '指令輸入',
    chipsLabel: '快速指令',
    skip: '跳到內容',
    themeButton: '切換光的色溫',
    langButton: '切換語言',
    welcome: '我讓軟體幕後的部分更可靠：不漏訊息、不重複執行、不覆蓋資料。',
    welcomeHint: ['輸入 ', { cmd: 'help' }, ' 或點選下方指令。Tab 可補全，↑ 可叫回上一個指令。'],
    boot: ['載入個人資料', '掛載 /projects', '就緒'],
    bootCount: (n) => `掛載 /projects（${n} 個公開儲存庫）`,
    cmds: {
      about: '我是誰、怎麼工作',
      projects: '我做過的東西（公開）',
      works: '其他值得一看的作品',
      gallery: '圖片與影片',
      photos: '我的攝影',
      view: '顯示一張圖片',
      work: '單一作品的詳情',
      skills: '我能幫上什麼',
      contact: '聯絡方式',
      ls: '列出檔案',
      cat: '顯示檔案內容',
      open: '在新分頁開啟連結',
      theme: 'auto | 5200k | 3400k | 2700k | 2200k',
      lang: 'en | zh',
      ascii: '會看著你的 ASCII 臉',
      '3d': '用文字畫出來的旋轉 3D 模型',
      transition: 'auto | dissolve | scan | rain | off',
      mode: '一次一頁，或像終端機一樣捲動（page | log）',
      mirror: '用字元畫出你自己（相機；影像只留在你的裝置）',
      clear: '清除畫面',
      history: '歷史指令',
      help: '顯示這份清單',
    },
    asciiLabel: '會動的 ASCII 臉',
    asciiHint: '移動游標：它會看著你。打字：它會聽。',
    modelLabel: (shape) => `旋轉的 ASCII 3D 模型：${shape}`,
    modelHint: ['移動游標可以控制轉動。試試 ', { cmd: '3d cube' }, '、', { cmd: '3d sphere' }, ' 或 ', { cmd: '3d donut' }, '。'],
    modelBad: (q, all) => `3d：未知的形狀「${q}」（可用：${all}）`,
    transitionCurrent: (cur, all) => `transition：${cur}（可用：${all}）`,
    transitionSet: (m) => `ASCII 轉場已切換為 ${m}`,
    transitionBad: (q, all) => `transition：未知的模式「${q}」（可用：${all}）`,
    mirror: {
      label: '相機鏡子',
      intro: '看看自己被畫成字元的樣子。只有在你按下按鈕之後，才會使用相機，而且只在這個頁面使用：畫面在你的裝置上轉成文字，不會被錄影、儲存，也不會傳到任何地方。',
      start: '▶ 開啟相機',
      stop: '■ 停止',
      copy: '把這一格複製成文字',
      copyShort: '複製成文字',
      fullscreen: '全螢幕',
      closeStage: '關閉並關掉相機',
      copied: '已把這一格複製成文字',
      copyFailed: '無法複製',
      hint: '按 Esc、✕ 或「停止」就會關閉相機。',
      starting: '等待相機…',
      slowStart: '還在等待。如果瀏覽器正在詢問權限，請選「允許」；或按「停止」再試一次。',
      live: '相機已開啟，不會錄影。',
      off: '相機已關閉。',
      pausedHidden: '這個分頁被隱藏了，所以相機已關閉。',
      lost: '相機已中斷連線。',
      errors: {
        denied: '相機被封鎖了。請在瀏覽器裡允許這個網站使用相機（看網址列的相機圖示），再試一次。',
        none: '這個裝置上找不到相機。',
        busy: '相機正被其他程式使用。',
        insecure: '相機只能在安全（https）的頁面使用。',
        unsupported: '這個瀏覽器無法從網頁開啟相機。',
        other: '無法啟動相機。',
      },
    },
    modeCurrent: (cur, all) => `mode：${cur}（可用：${all}；「page」像文件一樣一次顯示一頁，「log」保留每個指令的輸出、像傳統終端機一樣往下捲）`,
    modeSet: (m) => `mode ${m}`,
    modeBad: (q, all) => `mode：未知的模式「${q}」（可用：${all}）`,
    pages: { home: '首頁', about: '關於', projects: '專案', works: '作品', gallery: '圖片', photos: '攝影', skills: '技能', contact: '聯絡', help: '說明', mirror: '鏡子' },
    helpTitle: '可用指令',
    helpFooter: ['提示：', { cmd: 'ls' }, ' 列出檔案，', { cmd: 'cat about.md' }, ' 讀取檔案。快捷鍵：Tab、↑/↓、Ctrl+L。'],
    aboutTitle: 'about',
    bio: [
      '我是軟體工程師（後端／平台工程師）。協助已經有產品在運作的團隊，處理背後看不見的可靠性問題：資料庫、背景工作，以及系統各部分之間傳遞訊息的方式。',
      '我擅長找出「看起來有保護、其實不安全」的錯誤：同一件事可能偶爾做了兩次、漏掉，或是被覆蓋。例如訂單存好了卻沒通知倉庫，或同一則通知發了兩次。',
      '合作方式為固定範圍：先做診斷、檢視設計與程式碼、刻意把問題重現，再修復。所有結論都有文字紀錄，以非同步溝通為主，依里程碑付款。',
    ],
    workStyleTitle: '工作原則',
    workStyle: '我不只說「沒問題」，而是說明我怎麼知道。每個說法都對應到測試、文件，或老實註明哪些沒有主張。時間點或數字出了問題時，我讓它被看見，而不是被抹平。',
    aboutNext: ['接著看：', { cmd: 'projects' }, '、', { cmd: 'skills' }, '、', { cmd: 'contact' }],
    galleryTitle: 'gallery',
    galleryWorksHeading: '來自我的專案',
    galleryPhotosHeading: '攝影',
    photosTitle: 'photos',
    photosHint: (n) => ['執行 ', { cmd: `view ${n}` }, '（或名稱）。每張照片下方有拍攝資訊；點照片可以放大。'],
    galleryHint: ['執行 ', { cmd: 'view 1' }, '（或名稱）。畫面會先用文字畫出來，再變成真正的圖片；點圖片可以放大。'],
    viewUsage: ['用法：view <編號 | 名稱>（見 ', { cmd: 'gallery' }, '）'],
    noView: (q) => `view：找不到「${q}」`,
    viewer: {
      open: '放大檢視',
      close: '關閉',
      prev: '上一張',
      next: '下一張',
      counter: (i, n) => `${i} / ${n}`,
      source: '來源',
      play: '影片',
      related: '相關作品',
      pictures: '相關圖片',
      label: '圖片檢視器',
    },
    worksTitle: 'works',
    worksHint: ['執行 ', { cmd: 'work 1' }, '（或名稱）查看詳情。這些作品的描述不含私人名稱、合作對象或數字。'],
    workKinds: { visual: '視覺與 3D', thinking: '研究與思考', design: '設計' },
    workLabels: { kind: '類別', repo: '儲存庫' },
    workUsage: ['用法：work <編號 | 名稱>（見 ', { cmd: 'works' }, '）'],
    noWork: (q) => `work：找不到「${q}」`,
    projectsTitle: 'projects',
    projectsHint: ['公開專案。執行 ', { cmd: 'project 1' }, '（或名稱）查看詳情。'],
    projectLabels: { stack: '使用技術', repo: '儲存庫', notes: '不主張', tech: '給工程師' },
    skillsTitle: 'skills',
    contactTitle: 'contact',
    contactLabels: { github: 'github', email: 'email', mode: '方式' },
    contactCopy: '複製',
    contactButton: '複製 email 位址',
    contactCopied: '已複製 email 位址',
    contactFailed: (addr) => `無法自動複製，位址是 ${addr}`,
    contactMode: '用白話告訴我哪裡出了問題，以及你們用的系統（不確定也沒關係）。我會以文字回覆。',
    labels: { language: '語言', theme: '主題', role: '角色', repos: '儲存庫', shell: 'shell' },
    notFound: (c) => `找不到指令：${c}`,
    didYouMean: (c) => ['你是不是要輸入 ', { cmd: c }, '？'],
    tryHelp: ['輸入 ', { cmd: 'help' }, ' 查看所有指令。'],
    noFile: (p) => `cat: ${p}：沒有這個檔案或目錄`,
    isDir: (p) => `cat: ${p}：是一個目錄`,
    notDir: (p) => `ls: ${p}：不是目錄`,
    noSuchDir: (p) => `ls: ${p}：沒有這個檔案或目錄`,
    catUsage: ['用法：cat <檔案>（試試 ', { cmd: 'ls' }, '）'],
    noProject: (q) => `project：找不到「${q}」`,
    projectUsage: ['用法：project <編號 | 名稱>'],
    openUsage: (names) => `用法：open <${names}>`,
    openBad: (q) => `open：未知的目標「${q}」`,
    opening: (u) => `正在開啟 ${u}`,
    themeCurrent: (cur, all) => `主題：${cur}（可用：${all}）`,
    themeSet: (t) => `主題已切換為 ${t}`,
    themeBad: (q, all) => `theme：未知的主題「${q}」（可用：${all}）`,
    langCurrent: (cur) => `語言：${cur}（可用：en, zh）`,
    langSet: (n) => `語言已切換為 ${n}`,
    langBad: (q) => `lang：未知的語言「${q}」（可用：en, zh）`,
    historyEmpty: '尚無歷史指令',
    whoami: 'ezra，後端／平台工程師',
    sudo: 'ezra 不在 sudoers 名單中。此事件將被回報。',
    exit: '沒有出口，只有 `help`。',
    completions: '符合項目',
  },
};
